Use elm-review on the package
dillonkearns/elm-cli-options-parser pull request #20
Opened 2024-04-06 14:39 UTC by miniBill

Beside some cleanup, there is actually an important (minor version bump) change in there: exposing a couple alias types that are used in annotations, so that they can be named in user code.

2026-01-07 20:29 UTC, miniBill commented
Updated elm-review and fixed some new warnings

2026-01-08 18:52 UTC, dillonkearns commented
Sorry I tried upgrading the CI in master and merging it back in, but it was unhappy about the NPM optional dependencies for the Elm binary on Linux it seems?

2026-01-08 20:06 UTC, dillonkearns commented
Alright, got the CI running again! Looks like there are a couple of errors to address from the changes.

2026-01-11 04:58 UTC, dillonkearns requested changes
Thanks for the PR! I made one comment in a vendored file. Would be great to avoid changing any vendored files.

I'm also trying to understand the reason for the suppressed instances a bit better, could you give me a summary of the todo items that those represent?

2026-01-11 04:58 UTC, dillonkearns commented on src/Fuzzy.elm
I generally try not to touch vendored files and instead keep them exactly synced with the upstream unless there's a compelling reason not to. This is from https://github.com/tripokey/elm-fuzzy/blob/5.2.1/src/Fuzzy.elm. Could you revert the changes on this and ignore it in the elm-review config?

2026-01-13 13:32 UTC, miniBill commented on src/Fuzzy.elm
Reverted and ignored

2026-01-13 13:35 UTC, miniBill commented
The idea behind the suppressions is to split the work into this PR, which should contain the uncontroversial changes, and other PRs to fix the suppressions which may involve more discussions or choices or tradeoffs

2026-01-13 19:18 UTC, merged

2026-01-13 19:18 UTC, dillonkearns commented
Got it, sounds good to me! Thanks again for the PR 🙏